name: build for all targets and upload

on: workflow_dispatch
#on:
#  release:
#    types: [published]

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup python
        id: py310
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-deps -r requirements.txt
      - name: build app
        run: flet pack app.py --name llm-stack --product-name llm-stack --product-version ${{ github.event.release.tag_name }} --copyright "© 2023 hexis systems GmbH. Licensed under the MIT License."  --add-binary=${{ steps.py310.outputs.python-path }}/llama_cpp/libllama.so:llama_cpp
      - name: package app
        run: |
          sha256sum dist/app > CHECKSUM
          zip -r9 llm-stack-${{ github.event.release.tag_name }}-linux.zip dist/app/ CHECKSUM
      - name: upload app
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: llm-stack-${{ github.event.release.tag_name }}-linux.zip
          asset_name: llm-stack-${{ github.event.release.tag_name }}-linux.zip
          asset_content_type: application/zip

  build-macos:
    runs-on: macos-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup python
        run: |
          wget https://www.python.org/ftp/python/3.10.9/python-3.10.9-macos12.pkg
          sudo installer -pkg python-3.10.9-macos12.pkg -target /
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-deps -r requirements.txt
      - name: build app
        run: flet pack app.py --name llm-stack --product-name llm-stack --product-version ${{ github.event.release.tag_name }} --copyright "© 2023 hexis systems GmbH. Licensed under the MIT License."  --add-binary=/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/llama_cpp/libllama.dylib:llama_cpp
      - name: package app
        run: |
          sha256sum dist/llm-stack.app > CHECKSUM
          zip -r9 llm-stack-${{ github.event.release.tag_name }}-macos.zip dist/llm-stack.app/ CHECKSUM
      - name: upload app
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: llm-stack-${{ github.event.release.tag_name }}-macos.zip
          asset_name: llm-stack-${{ github.event.release.tag_name }}-macos.zip
          asset_content_type: application/zip

  build-windows:
    runs-on: windows-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup python
        id: py310
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-deps -r requirements.txt
      - name: build app
        run: flet pack app.py --name llm-stack --product-name llm-stack --product-version ${{ github.event.release.tag_name }} --copyright "© 2023 hexis systems GmbH. Licensed under the MIT License."  --add-binary=${{ steps.py310.outputs.python-path }}\llama_cpp\libllama.dll:llama_cpp
      - name: package app
        run: |
          sha256sum dist\llm-stack.exe > CHECKSUM
          zip -r9 llm-stack-${{ github.event.release.tag_name }}-windows.zip dist\llm-stack.exe CHECKSUM
      - name: upload app
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: llm-stack-${{ github.event.release.tag_name }}-windows.zip
          asset_name: llm-stack-${{ github.event.release.tag_name }}-windows.zip
          asset_content_type: application/zip